name: My Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Wheezy!"
      -name: Print goodbye
        run: echo "Done-zo, son. Peace out!"
      
